# Loaded by testthat before every test file.

# Source the analytics modules relative to this file, so the suite runs from
# any working directory.
local({
  here <- dirname(dirname(dirname(normalizePath(
    sys.frame(1)$ofile %||% "tests/testthat/helper-augury.R",
    mustWork = FALSE
  ))))

  candidates <- c(
    file.path(here, "R"),
    file.path("..", "..", "R"),
    "R"
  )

  for (dir in candidates) {
    if (dir.exists(dir)) {
      for (file in list.files(dir, pattern = "\\.R$", full.names = TRUE)) {
        source(file, local = FALSE)
      }
      break
    }
  }
})

#' Locate the shared cross-language golden vectors.
#'
#' Returns NULL when absent so tests can skip rather than fail — the file is
#' generated by `python -m augury_signal.golden` and may not exist in a
#' checkout where only the R toolchain is installed.
find_golden_vectors <- function() {
  current <- normalizePath(getwd(), mustWork = FALSE)

  for (depth in seq_len(8)) {
    candidate <- file.path(current, "schemas", "testdata", "golden_vectors.json")
    if (file.exists(candidate)) {
      return(candidate)
    }
    parent <- dirname(current)
    if (identical(parent, current)) break
    current <- parent
  }
  NULL
}

`%||%` <- function(x, y) if (is.null(x)) y else x
